#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfDataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cf")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CfDataContext.Properties.Settings.Default.CfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EmployeeProductCalculator", IsComposable=true)]
		public IQueryable<EmployeeProductCalculatorResult> EmployeeProductCalculator([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeId", DbType="Int")] System.Nullable<int> employeeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductTypeId", DbType="SmallInt")] System.Nullable<short> productTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Period", DbType="SmallInt")] System.Nullable<short> period)
		{
			return this.CreateMethodCallQuery<EmployeeProductCalculatorResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employeeId, productTypeId, amount, period);
		}
	}
	
	public partial class EmployeeProductCalculatorResult
	{
		
		private System.Nullable<int> _EmployeeId;
		
		private System.Nullable<decimal> _MaxAmount;
		
		private System.Nullable<short> _Seniority;
		
		private System.Nullable<byte> _MinSeniority;
		
		private System.Nullable<byte> _MinReusePeriod;
		
		private System.Nullable<short> _ProductTypeId;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<decimal> _NetAmount;
		
		private System.Nullable<decimal> _ProfitAmount;
		
		private System.Nullable<decimal> _Installment;
		
		private System.Nullable<double> _Rate;
		
		private System.Nullable<byte> _GuarantorsCount;
		
		public EmployeeProductCalculatorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int")]
		public System.Nullable<int> EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this._EmployeeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAmount", DbType="Money")]
		public System.Nullable<decimal> MaxAmount
		{
			get
			{
				return this._MaxAmount;
			}
			set
			{
				if ((this._MaxAmount != value))
				{
					this._MaxAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seniority", DbType="SmallInt")]
		public System.Nullable<short> Seniority
		{
			get
			{
				return this._Seniority;
			}
			set
			{
				if ((this._Seniority != value))
				{
					this._Seniority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinSeniority", DbType="TinyInt")]
		public System.Nullable<byte> MinSeniority
		{
			get
			{
				return this._MinSeniority;
			}
			set
			{
				if ((this._MinSeniority != value))
				{
					this._MinSeniority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinReusePeriod", DbType="TinyInt")]
		public System.Nullable<byte> MinReusePeriod
		{
			get
			{
				return this._MinReusePeriod;
			}
			set
			{
				if ((this._MinReusePeriod != value))
				{
					this._MinReusePeriod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeId", DbType="SmallInt")]
		public System.Nullable<short> ProductTypeId
		{
			get
			{
				return this._ProductTypeId;
			}
			set
			{
				if ((this._ProductTypeId != value))
				{
					this._ProductTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetAmount", DbType="Money")]
		public System.Nullable<decimal> NetAmount
		{
			get
			{
				return this._NetAmount;
			}
			set
			{
				if ((this._NetAmount != value))
				{
					this._NetAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfitAmount", DbType="Money")]
		public System.Nullable<decimal> ProfitAmount
		{
			get
			{
				return this._ProfitAmount;
			}
			set
			{
				if ((this._ProfitAmount != value))
				{
					this._ProfitAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Installment", DbType="Money")]
		public System.Nullable<decimal> Installment
		{
			get
			{
				return this._Installment;
			}
			set
			{
				if ((this._Installment != value))
				{
					this._Installment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Float")]
		public System.Nullable<double> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this._Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuarantorsCount", DbType="TinyInt")]
		public System.Nullable<byte> GuarantorsCount
		{
			get
			{
				return this._GuarantorsCount;
			}
			set
			{
				if ((this._GuarantorsCount != value))
				{
					this._GuarantorsCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
